-- CREATE TABLE INVENTORY:
CREATE TABLE inventory (
	id SERIAL PRIMARY KEY,
	product_id UUID NOT NULL,
	quantity INTEGER NOT NULL,
	name VARCHAR(255) NOT NULL,
	price INTEGER NOT NULL,
	"desc" TEXT,
	status INTEGER NOT NULL,
	revision INTEGER NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER update_db_timestamp BEFORE UPDATE
ON inventory
FOR EACH ROW
EXECUTE PROCEDURE update_timestamp();

-- CREATE TABLE CHECKPOINT:
CREATE TABLE checkpoint (
	id VARCHAR(255) PRIMARY KEY,
	position TEXT NOT NULL
);
